spring.application.name=erp
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=strict
# 1. Datos de conexión
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME:erp_db}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:admin123}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.open-in-view=false

# 2. Estrategia de creación de tablas (JPA/Hibernate)
spring.jpa.hibernate.ddl-auto=update

# 3. Mostrar las consultas SQL en la consola (útil para aprender)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 4. config para desarro spring devtools (eliminar en producción)
spring.thymeleaf.cache=false
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# 5. Variables de entorno para crear el primer admin si la variable de entorno no existe, usará los valores después de ':'
app.admin.username=${ERP_ADMIN_USER:admin}
app.admin.useremail=${ERP_ADMIN_EMAIL:admin@gmail.com}
app.admin.password=${ERP_ADMIN_PASS:admin123}